import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
    const caItems = [
        {
            code: "CA-001-A",
            name: "Medidor de nível de pressão sonora (Kit CA-001)",
            manufacturer: "Bruel Kjaer",
            model: "2270",
            serialNumber: "3003751",
            testType: "Acústica",
            location: "Sala de Equipamentos",
            lab: "Lacel B&K",
            certificateNumber: ["CBR2500549"],
            serviceType: ["Calibração"],
            lastCalibrationDate: new Date("2025-08-25"),
            calibrationInterval: 24,
            nextCalibrationDate: new Date("2027-08-26"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-001-B",
            name: "Microfone (Kit CA-001)",
            manufacturer: "Bruel Kjaer",
            model: "4189",
            serialNumber: "2876982",
            testType: "Acústica",
            location: "Sala de Equipamentos",
            lab: "Lacel B&K",
            certificateNumber: ["CBR2500549"],
            serviceType: ["Calibração"],
            lastCalibrationDate: new Date("2025-08-25"),
            calibrationInterval: 24,
            nextCalibrationDate: new Date("2027-08-26"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-001-C",
            name: "Pré Amplificador (Kit CA-001)",
            manufacturer: "Bruel Kjaer",
            model: "ZC-0032",
            serialNumber: "19345",
            testType: "Acústica",
            location: "Sala de Equipamentos",
            lab: "Lacel B&K",
            certificateNumber: ["CBR2500549"],
            serviceType: ["Calibração"],
            lastCalibrationDate: new Date("2025-08-25"),
            calibrationInterval: 24,
            nextCalibrationDate: new Date("2027-08-26"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-002-A",
            name: "Medidor de nível de pressão sonora (Kit CA-002)",
            manufacturer: "Bruel Kjaer",
            model: "2270",
            serialNumber: "3003751",
            testType: "Acústica",
            location: "Sala de Equipamentos",
            lab: "Lacel B&K",
            certificateNumber: ["CBR2500550"],
            serviceType: ["Calibração"],
            lastCalibrationDate: new Date("2025-08-25"),
            calibrationInterval: 24,
            nextCalibrationDate: new Date("2027-08-26"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-002-B",
            name: "Microfone (Kit CA-002)",
            manufacturer: "Bruel Kjaer",
            model: "4966",
            serialNumber: "3323031",
            testType: "Acústica",
            location: "Sala de Equipamentos",
            lab: "Lacel B&K",
            certificateNumber: ["CBR2500550"],
            serviceType: ["Calibração"],
            lastCalibrationDate: new Date("2025-08-25"),
            calibrationInterval: 24,
            nextCalibrationDate: new Date("2027-08-26"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-002-C",
            name: "Pré Amplificador (Kit CA-002)",
            manufacturer: "Bruel Kjaer",
            model: "ZC-0032",
            serialNumber: "19611",
            testType: "Acústica",
            location: "Sala de Equipamentos",
            lab: "Lacel B&K",
            certificateNumber: ["CBR2500550"],
            serviceType: ["Calibração"],
            lastCalibrationDate: new Date("2025-08-25"),
            calibrationInterval: 24,
            nextCalibrationDate: new Date("2027-08-26"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-003",
            name: "Calibrador acústico",
            manufacturer: "Bruel Kjaer",
            model: "4231",
            serialNumber: "3006768",
            testType: "Acústica",
            location: "Sala de Equipamentos",
            lab: "Teslab",
            certificateNumber: ["2/2025"],
            serviceType: ["Calibração"],
            lastCalibrationDate: new Date("2025-01-08"),
            calibrationInterval: 24,
            nextCalibrationDate: new Date("2027-01-08"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-004",
            name: "Trena",
            manufacturer: "XBE",
            model: "10m",
            range: "0 a 10m",
            testType: "Aderência",
            location: "Sala de Equipamentos",
            lab: "Qualitest",
            certificateNumber: ["113/2025"],
            serviceType: ["Calibração"],
            lastCalibrationDate: new Date("2025-01-06"),
            calibrationInterval: 60,
            nextCalibrationDate: new Date("2031-01-06"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-005",
            name: "Medidor de Umidade Superficial",
            manufacturer: "Testo",
            model: "606-1",
            serialNumber: "38666571/512",
            testType: "Aderência",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["101250/23"],
            serviceType: ["Calibração"],
            lastCalibrationDate: new Date("2023-06-30"),
            calibrationInterval: 60,
            nextCalibrationDate: new Date("2028-06-30"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-006",
            name: "Aderímetro",
            manufacturer: "Solotest",
            range: "1.500 kgf",
            testType: "Aderência",
            location: "Depósito",
            lab: "Metroquality",
            certificateNumber: ["7683/2019"],
            serviceType: ["Calibração"],
            lastCalibrationDate: new Date("2019-04-17"),
            calibrationInterval: 12,
            nextCalibrationDate: new Date("2020-04-17"),
            acceptance: "Reprovado",
            status: "VENCIDO"
        },
        {
            code: "CA-007",
            name: "Aderímetro",
            manufacturer: "Solotest",
            serialNumber: "1129010 / 24584",
            range: "1.500 kgf",
            testType: "Aderência",
            location: "Sala de Equipamentos",
            lab: "SENAI",
            certificateNumber: ["180/25"],
            serviceType: ["Calibração"],
            lastCalibrationDate: new Date("2025-01-23"),
            calibrationInterval: 12,
            nextCalibrationDate: new Date("2026-01-23"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-008",
            name: "Paquímetro Digital",
            manufacturer: "MTX",
            model: "Digital",
            serialNumber: "316119",
            range: "1 a 150mm",
            testType: "Guarda-corpo",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["104/2025"],
            serviceType: ["Calibração"],
            lastCalibrationDate: new Date("2025-01-06"),
            calibrationInterval: 12,
            nextCalibrationDate: new Date("2026-01-06"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-009",
            name: "Paquímetro Digital",
            manufacturer: "MTX",
            model: "Digital",
            serialNumber: "316119",
            testType: "Guarda-corpo",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["103/2025"],
            serviceType: ["Calibração"],
            lastCalibrationDate: new Date("2025-01-06"),
            calibrationInterval: 12,
            nextCalibrationDate: new Date("2026-01-06"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-010-A",
            name: "Saco de couro esferas de vidro",
            manufacturer: "artesanal",
            range: "Ø 30cm",
            testType: "Guarda-corpo",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["4287/2025"],
            serviceType: ["Massa"],
            lastCalibrationDate: new Date("2025-03-10"),
            calibrationInterval: 60,
            nextCalibrationDate: new Date("2030-03-10"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-010-B",
            name: "Saco de couro esferas de vidro",
            manufacturer: "artesanal",
            range: "Ø 30cm",
            testType: "Guarda-corpo",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["4288/2025"],
            serviceType: ["Massa"],
            lastCalibrationDate: new Date("2025-03-10"),
            calibrationInterval: 60,
            nextCalibrationDate: new Date("2030-03-10"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-011-A",
            name: "Saco de couro serragem e areia",
            manufacturer: "artesanal",
            range: "Ø 35cm",
            testType: "Corpo mole e duro",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["030840/2024"],
            serviceType: ["Massa"],
            lastCalibrationDate: new Date("2024-08-23"),
            calibrationInterval: 60,
            nextCalibrationDate: new Date("2029-08-23"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-011-B",
            name: "Saco de couro serragem e areia",
            manufacturer: "artesanal",
            range: "Ø 35cm",
            testType: "Corpo mole e duro",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["030960/2024"],
            serviceType: ["Massa"],
            lastCalibrationDate: new Date("2024-08-23"),
            calibrationInterval: 60,
            nextCalibrationDate: new Date("2029-08-23"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-012",
            name: "Esfera de aço 0,5 kg",
            manufacturer: "artesanal",
            range: "Ø 50mm",
            testType: "Corpo mole e duro",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["101259-23"],
            serviceType: ["Massa"],
            lastCalibrationDate: new Date("2023-06-30"),
            calibrationInterval: 60,
            nextCalibrationDate: new Date("2028-06-30"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-013",
            name: "Esfera de aço 1,0 kg",
            manufacturer: "artesanal",
            range: "Ø 55mm",
            testType: "Corpo mole e duro",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["101257-23"],
            serviceType: ["Massa"],
            lastCalibrationDate: new Date("2023-06-30"),
            calibrationInterval: 60,
            nextCalibrationDate: new Date("2028-06-30"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-014",
            name: "Molde padrão em alumínio",
            manufacturer: "artesanal",
            testType: "Guarda-corpo",
            location: "Armário 02",
            lab: "Metroquality",
            certificateNumber: ["51157/21"],
            serviceType: ["Massa"],
            lastCalibrationDate: new Date("2021-07-12"),
            calibrationInterval: 60,
            nextCalibrationDate: new Date("2026-07-12"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-015",
            name: "Bomba hidráulica manual",
            manufacturer: "Torvel",
            model: "EN 837-1",
            serialNumber: "E16003808453",
            range: "0 a 140kgf/cm²",
            testType: "Força",
            location: "Armário 02",
            lab: "Qualisul",
            certificateNumber: ["66761/22"],
            serviceType: ["Força"],
            lastCalibrationDate: new Date("2022-03-30"),
            calibrationInterval: 12,
            nextCalibrationDate: new Date("2023-03-30"),
            acceptance: "Vencido",
            status: "VENCIDO"
        },
        {
            code: "CA-016",
            name: "Equipamento de PIT",
            manufacturer: "Profound",
            model: "SIT",
            serialNumber: "62503",
            range: "500 m/s²",
            testType: "PIT",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["8226/2025"],
            serviceType: ["Velocidade"],
            lastCalibrationDate: new Date("2025-04-28"),
            calibrationInterval: 60,
            nextCalibrationDate: new Date("2030-04-28"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-017",
            name: "Esclerômetro",
            manufacturer: "Proceq",
            model: "TYPE N",
            serialNumber: "SH01-004-0337",
            range: "202 a 718kg/cm²",
            testType: "Esclerometria",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["901/2025"],
            serviceType: ["Força"],
            lastCalibrationDate: new Date("2025-01-19"),
            calibrationInterval: 24,
            nextCalibrationDate: new Date("2027-01-19"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-018",
            name: "Termovisor",
            manufacturer: "FLIR",
            model: "T450sc",
            serialNumber: "62111724",
            range: "até 1500°C",
            testType: "Termografia",
            location: "Sala de Equipamentos",
            lab: "Fir System",
            certificateNumber: ["171300"],
            serviceType: ["Temperatura"],
            lastCalibrationDate: new Date("2017-08-24"),
            calibrationInterval: 60,
            nextCalibrationDate: new Date("2022-08-24"),
            acceptance: "Vencido",
            status: "VENCIDO"
        },
        {
            code: "CA-019",
            name: "Luxímetro digital",
            manufacturer: "Instrutherm",
            model: "LDR - 225",
            serialNumber: "121207370",
            range: "20 a 2000lx",
            testType: "Lumínico",
            location: "Sala de Equipamentos",
            lab: "Labelo Pucrs",
            certificateNumber: ["L0023/2025"],
            serviceType: ["Óptica"],
            lastCalibrationDate: new Date("2025-04-08"),
            calibrationInterval: 36,
            nextCalibrationDate: new Date("2028-04-08"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-020",
            name: "Equipamento hidráulico para ancoragem",
            manufacturer: "Gulton",
            range: "0 a 1999kgf",
            testType: "Ancoragem",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["74192-22"],
            serviceType: ["Força"],
            lastCalibrationDate: new Date("2022-07-14"),
            calibrationInterval: 12,
            nextCalibrationDate: new Date("2023-07-14"),
            acceptance: "Vencido",
            status: "VENCIDO"
        },
        {
            code: "CA-021",
            name: "Relógio Comparador",
            manufacturer: "Mitutoyo",
            model: "575-122",
            serialNumber: "17066988",
            range: "0 a 25mm",
            testType: "Guarda-corpo",
            location: "Armário 02",
            lab: "Qualisul",
            certificateNumber: ["117/2025"],
            serviceType: ["Dimensional"],
            lastCalibrationDate: new Date("2025-01-06"),
            calibrationInterval: 12,
            nextCalibrationDate: new Date("2026-01-06"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-022",
            name: "Relógio Comparador",
            manufacturer: "Mitutoyo",
            model: "575-122",
            serialNumber: "17202254",
            range: "0 a 25mm",
            testType: "Guarda-corpo",
            location: "Armário 02",
            lab: "Qualisul",
            certificateNumber: ["119/2025"],
            serviceType: ["Dimensional"],
            lastCalibrationDate: new Date("2025-01-06"),
            calibrationInterval: 12,
            nextCalibrationDate: new Date("2026-01-06"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-023",
            name: "Relógio Comparador",
            manufacturer: "Mitutoyo",
            model: "575-122",
            serialNumber: "17889573",
            range: "0 a 25mm",
            testType: "Guarda-corpo",
            location: "Armário 02",
            lab: "Qualisul",
            certificateNumber: ["118/2025"],
            serviceType: ["Dimensional"],
            lastCalibrationDate: new Date("2025-01-06"),
            calibrationInterval: 12,
            nextCalibrationDate: new Date("2026-01-06"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-024",
            name: "Relógio Comparador",
            manufacturer: "Mitutoyo",
            model: "575-122",
            serialNumber: "17202252",
            range: "0 a 25mm",
            testType: "Guarda-corpo",
            location: "Armário 02",
            lab: "Qualisul",
            certificateNumber: ["115/2025"],
            serviceType: ["Dimensional"],
            lastCalibrationDate: new Date("2025-01-06"),
            calibrationInterval: 12,
            nextCalibrationDate: new Date("2026-01-06"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-025",
            name: "Trena",
            manufacturer: "Lufkin",
            serialNumber: "1716",
            range: "0 x 5m",
            testType: "Guarda-corpo",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["72385/22"],
            serviceType: ["Dimensional"],
            lastCalibrationDate: new Date("2022-06-22"),
            calibrationInterval: 12,
            nextCalibrationDate: new Date("2023-06-22"),
            acceptance: "Vencido",
            status: "VENCIDO"
        },
        {
            code: "CA-026",
            name: "Paquímetro Digital",
            manufacturer: "MTX",
            model: "Digital",
            serialNumber: "316119",
            range: "1 a 150mm",
            testType: "Aderência",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["756/2026"],
            serviceType: ["Dimensional"],
            lastCalibrationDate: new Date("2025-01-16"),
            calibrationInterval: 12,
            nextCalibrationDate: new Date("2026-01-16"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-027",
            name: "Aderímetro",
            manufacturer: "Solotest",
            serialNumber: "14343",
            range: "0 a 600kgf",
            testType: "Aderência",
            location: "Depósito",
            lab: "Qualisul",
            certificateNumber: ["30308/20"],
            serviceType: ["Força"],
            lastCalibrationDate: new Date("2020-06-19"),
            calibrationInterval: 12,
            nextCalibrationDate: new Date("2021-06-19"),
            acceptance: "Vencido",
            status: "VENCIDO"
        },
        {
            code: "CA-028",
            name: "Câmara Acústica",
            manufacturer: "CAE",
            serialNumber: "100380",
            testType: "Acústica",
            location: "Sala de Equipamentos",
            serviceType: ["Acústica"],
            status: "VENCIDO",
            acceptance: "Não calibrado"
        },
        {
            code: "CA-029-A",
            name: "Medidor de pressão sonora (Kit CA-029)",
            manufacturer: "01 dB",
            model: "Fusion 2.0",
            serialNumber: "12947",
            range: "21 a 139 dB",
            testType: "Acústica",
            location: "Sala de Equipamentos",
            lab: "Caliblab",
            certificateNumber: ["RBC10-12880-560"],
            serviceType: ["Acústica"],
            lastCalibrationDate: new Date("2024-08-30"),
            calibrationInterval: 24,
            nextCalibrationDate: new Date("2026-08-30"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-029-B",
            name: "Microfone (Kit CA-029)",
            manufacturer: "G.R.A.S",
            model: "40CE",
            serialNumber: "449409",
            testType: "Acústica",
            location: "Sala de Equipamentos",
            lab: "Caliblab",
            certificateNumber: ["RBC10-12881-336"],
            serviceType: ["Acústica"],
            lastCalibrationDate: new Date("2024-09-02"),
            calibrationInterval: 24,
            nextCalibrationDate: new Date("2026-09-02"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-029-C",
            name: "Pró Amplificador (Kit CA-029)",
            manufacturer: "01 dB",
            serialNumber: "95015",
            testType: "Acústica",
            location: "Sala de Equipamentos",
            lab: "Caliblab",
            certificateNumber: ["RBC10-12882-338"],
            serviceType: ["Acústica"],
            lastCalibrationDate: new Date("2024-08-02"),
            calibrationInterval: 24,
            nextCalibrationDate: new Date("2026-08-02"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-030",
            name: "Calibrador acústico",
            manufacturer: "01 dB",
            model: "Cal31",
            serialNumber: "95015",
            range: "93,7 e 114 dB",
            testType: "Acústica",
            location: "Sala de Equipamentos",
            lab: "Teslab",
            certificateNumber: ["324/2024"],
            serviceType: ["Acústica"],
            lastCalibrationDate: new Date("2024-08-09"),
            calibrationInterval: 24,
            nextCalibrationDate: new Date("2026-08-09"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-031",
            name: "Termo-higro-Anemômetro Digital",
            manufacturer: "AKSO",
            model: "AK821",
            serialNumber: "VA200111562",
            testType: "Acústica",
            location: "Sala de Equipamentos",
            lab: "AKSO",
            certificateNumber: ["14387/2021"],
            serviceType: ["Velocidade/Umidade/Temp"],
            lastCalibrationDate: new Date("2021-05-27"),
            calibrationInterval: 36,
            nextCalibrationDate: new Date("2024-05-27"),
            acceptance: "Vencido",
            status: "VENCIDO"
        },
        {
            code: "CA-032",
            name: "Célula de Carga",
            manufacturer: "Líder Balanças",
            model: "PR20/500",
            serialNumber: "86846",
            range: "0 a 500kgf",
            testType: "Guarda-corpo",
            location: "Sala de Equipamentos",
            lab: "SENAI",
            certificateNumber: ["234/25"],
            serviceType: ["Força"],
            lastCalibrationDate: new Date("2025-01-25"),
            calibrationInterval: 12,
            nextCalibrationDate: new Date("2027-01-26"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-033",
            name: "Célula de Carga",
            manufacturer: "Líder Balanças",
            model: "PR20/500",
            serialNumber: "86847",
            range: "0 a 500kgf",
            testType: "Guarda-corpo",
            location: "Sala de Equipamentos",
            lab: "SENAI",
            certificateNumber: ["235/25"],
            serviceType: ["Força"],
            lastCalibrationDate: new Date("2025-01-25"),
            calibrationInterval: 12,
            nextCalibrationDate: new Date("2027-01-26"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-034",
            name: "Célula de Carga",
            manufacturer: "Líder Balanças",
            model: "PR20/500",
            serialNumber: "86848",
            range: "0 a 500kgf",
            testType: "Guarda-corpo",
            location: "Sala de Equipamentos",
            lab: "SENAI",
            certificateNumber: ["232/25"],
            serviceType: ["Força"],
            lastCalibrationDate: new Date("2025-01-25"),
            calibrationInterval: 12,
            nextCalibrationDate: new Date("2027-01-26"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-035",
            name: "Termo-Higro-Anemômetro-Luxímetro-Decibelímetro",
            manufacturer: "Akrom",
            model: "KR-500",
            serialNumber: "20170805112",
            range: "0 a 200k lux",
            testType: "Lumínico",
            location: "Sala de Equipamentos",
            lab: "Labelo Pucrs",
            certificateNumber: ["L0024/2025"],
            serviceType: ["Óptica"],
            lastCalibrationDate: new Date("2025-04-08"),
            calibrationInterval: 24,
            nextCalibrationDate: new Date("2028-04-08"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-036",
            name: "Bureta 25 mL",
            manufacturer: "DiogoLab",
            range: "0 a 25ml",
            testType: "Permeabilidade",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["76895-22"],
            serviceType: ["Volume"],
            lastCalibrationDate: new Date("2022-08-22"),
            calibrationInterval: 60,
            nextCalibrationDate: new Date("2027-08-22"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-037",
            name: "Bureta 50 mL",
            manufacturer: "DiogoLab",
            range: "0 a 50ml",
            testType: "Permeabilidade",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["76894-22"],
            serviceType: ["Volume"],
            lastCalibrationDate: new Date("2022-08-19"),
            calibrationInterval: 60,
            nextCalibrationDate: new Date("2027-08-19"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-038",
            name: "Caixa acrílica",
            manufacturer: "artesanal",
            testType: "Permeabilidade",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["76899-22"],
            serviceType: ["Dimensional"],
            lastCalibrationDate: new Date("2022-08-19"),
            calibrationInterval: 60,
            nextCalibrationDate: new Date("2027-08-19"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-039",
            name: "Cachimbo de vidro",
            manufacturer: "artesanal",
            range: "0 a 4ml",
            testType: "Permeabilidade",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["76906-22"],
            serviceType: ["Volume"],
            lastCalibrationDate: new Date("2022-08-22"),
            calibrationInterval: 60,
            nextCalibrationDate: new Date("2027-08-22"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-041",
            name: "Caixa acrílica",
            manufacturer: "artesanal",
            testType: "Permeabilidade",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["76898-22"],
            serviceType: ["Dimensional"],
            lastCalibrationDate: new Date("2022-08-19"),
            calibrationInterval: 60,
            nextCalibrationDate: new Date("2027-08-19"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-042",
            name: "Molde padrão em madeira",
            manufacturer: "artesanal",
            testType: "Guarda-corpo",
            location: "Armário 02",
            lab: "Qualisul",
            certificateNumber: ["40248/2024"],
            serviceType: ["Dimensional"],
            lastCalibrationDate: new Date("2024-12-20"),
            calibrationInterval: 60,
            nextCalibrationDate: new Date("2029-12-20"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-044",
            name: "Termômetro Monitor de Umidade",
            manufacturer: "Acurite",
            model: "1083",
            serialNumber: "01083M",
            range: "1 a 99%UR",
            testType: "Acústica",
            location: "Sala de Equipamentos",
            lab: "Metroquality",
            certificateNumber: ["8248/25"],
            serviceType: ["Umidade/Temperatura"],
            lastCalibrationDate: new Date("2025-03-18"),
            calibrationInterval: 24,
            nextCalibrationDate: new Date("2027-03-18"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-045",
            name: "Termômetro Monitor de Umidade",
            manufacturer: "Acurite",
            model: "1083",
            serialNumber: "01083M",
            range: "1 a 99%UR",
            testType: "Acústica",
            location: "Sala de Equipamentos",
            lab: "Metroquality",
            certificateNumber: ["8246/25"],
            serviceType: ["Umidade/Temperatura"],
            lastCalibrationDate: new Date("2025-03-18"),
            calibrationInterval: 24,
            nextCalibrationDate: new Date("2027-03-18"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-046",
            name: "Trena",
            manufacturer: "Yijialin",
            model: "ZL2018",
            serialNumber: "3 027280.7",
            range: "5m",
            testType: "Guarda-corpo",
            location: "Armário 02",
            lab: "Qualisul",
            certificateNumber: ["105/2025"],
            serviceType: ["Dimensional"],
            lastCalibrationDate: new Date("2025-01-25"),
            calibrationInterval: 24,
            nextCalibrationDate: new Date("2027-01-25"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-047",
            name: "Equipamento hidráulico para ancoragem",
            manufacturer: "Dois Dez",
            model: "MA.17194",
            range: "300kgf/cm²",
            testType: "Ancoragem",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["109/2025"],
            serviceType: ["Força"],
            lastCalibrationDate: new Date("2025-01-06"),
            calibrationInterval: 24,
            nextCalibrationDate: new Date("2027-01-06"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-048",
            name: "Aderímetro",
            manufacturer: "Solotest",
            model: "1129005",
            serialNumber: "31010",
            range: "0 a 500kgf",
            testType: "Aderência",
            location: "Sala de Equipamentos",
            lab: "SENAI",
            certificateNumber: ["598/25"],
            serviceType: ["Força"],
            lastCalibrationDate: new Date("2025-03-04"),
            calibrationInterval: 24,
            nextCalibrationDate: new Date("2027-03-04"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-049",
            name: "Paquímetro Digital",
            manufacturer: "MTX",
            model: "Digital",
            serialNumber: "316119",
            range: "1 a 150mm",
            testType: "Aderência",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["101/2025"],
            serviceType: ["Dimensional"],
            lastCalibrationDate: new Date("2025-01-06"),
            calibrationInterval: 24,
            nextCalibrationDate: new Date("2027-01-06"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-050",
            name: "Aderímetro",
            manufacturer: "Solotest",
            model: "1.129.010",
            serialNumber: "24584",
            range: "0 a 1.500kgf",
            testType: "Aderência",
            location: "Sala de Equipamentos",
            lab: "Solotest",
            certificateNumber: ["81097-25"],
            serviceType: ["Força"],
            lastCalibrationDate: new Date("2025-05-19"),
            calibrationInterval: 12,
            nextCalibrationDate: new Date("2026-05-19"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-051",
            name: "Relógio Comparador",
            serialNumber: "DH19255",
            range: "0 a 100mm",
            testType: "Guarda-corpo",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["110/2026"],
            serviceType: ["Dimensional"],
            lastCalibrationDate: new Date("2025-01-06"),
            calibrationInterval: 24,
            nextCalibrationDate: new Date("2027-01-06"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-052",
            name: "Relógio Comparador",
            serialNumber: "EB131191",
            range: "1 a 100mm",
            testType: "Guarda-corpo",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["106/2025"],
            serviceType: ["Dimensional"],
            lastCalibrationDate: new Date("2025-01-06"),
            calibrationInterval: 24,
            nextCalibrationDate: new Date("2027-01-06"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-053",
            name: "Relógio Comparador",
            serialNumber: "DL140735",
            range: "2 a 100mm",
            testType: "Guarda-corpo",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["111/2026"],
            serviceType: ["Dimensional"],
            lastCalibrationDate: new Date("2025-01-06"),
            calibrationInterval: 24,
            nextCalibrationDate: new Date("2027-01-06"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-054",
            name: "Relógio Comparador",
            manufacturer: "Digimess",
            model: "121.339",
            serialNumber: "24F00021",
            range: "3 a 100mm",
            testType: "Guarda-corpo",
            location: "Sala de Equipamentos",
            lab: "Qualisul",
            certificateNumber: ["112/2025"],
            serviceType: ["Dimensional"],
            lastCalibrationDate: new Date("2025-01-06"),
            calibrationInterval: 24,
            nextCalibrationDate: new Date("2027-01-06"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-055",
            name: "Aderímetro",
            manufacturer: "Solotest",
            model: "1.129.010",
            serialNumber: "37347",
            range: "0 a 1.500 kgf",
            testType: "Aderência",
            location: "Sala de Equipamentos",
            lab: "Solotest",
            certificateNumber: ["84693-25"],
            serviceType: ["Força"],
            lastCalibrationDate: new Date("2025-12-16"),
            calibrationInterval: 12,
            nextCalibrationDate: new Date("2026-12-16"),
            acceptance: "Aprovado",
            status: "ATIVO"
        },
        {
            code: "CA-056",
            name: "Acelerômetro monoaxial",
            manufacturer: "B&K",
            model: "4533-B",
            serialNumber: "33565",
            range: "10Hz a 10kHz",
            testType: "acústica",
            location: "Sala de Equipamentos",
            lab: "B&K",
            certificateNumber: ["CBR2500095"],
            serviceType: ["Excitação"],
            lastCalibrationDate: new Date("2025-02-19"),
            calibrationInterval: 36,
            nextCalibrationDate: new Date("2028-02-19"),
            acceptance: "Aprovado",
            status: "ATIVO"
        }
    ]

    const eqItems = [
        "Amortecedor", "Amortecedor", "Adaptador para microfone", "Tripé de madeira", "Tripé de madeira", 
        "Tripé de madeira", "Amplificador acústico de potência", "Tripé telescópico para microfone", 
        "Tripé para microfone", "Suporte para microfone", "Suporte para microfone", 
        "Cabo de extensão de microfone", "Cabo de extensão de microfone", "Transformador de rede", 
        "Cabo rede", "Cabo rede", "Maleta de transporte para medidor", "Protetor de vento para microfone", 
        "Kit de transporte para medidor", "Bateria recarregável", "Bateria recarregável", 
        "Cabo de conexão medidor/PC", "Software de análise", "Módulo de hardware", "Módulo de hardware", 
        "Cabo de alimentação", "Cabo de alimentação", "Adaptador de rede", "Bolsa de transporte", 
        "Suporte tripolar para dinamômetro", "Base de apoio", "Peso 20kg", "Peso 20kg", "Peso 20kg", 
        "Peso 20kg", "Peso 20kg", "Peso 20kg", "Peso 20kg", "Peso 20kg", "Peso 20kg", "Peso 20kg", 
        "Peso 20kg", "Peso 10kg", "Peso 10kg", "Peso 10kg", "Peso 10kg", "Peso 10kg", "Peso 10kg", 
        "Peso 5kg", "Peso 5kg", "Peso 5kg", "Peso 5kg", "Peso 2kg", "Peso 2kg", "Peso 2kg", 
        "Peso 2kg", "Peso 1kg", "Peso 1kg", "Peso 1kg", "Peso 1kg", "Peso 500g", "Peso 500g", 
        "Peso 200g", "Peso 200g", "Peso 100g", "Peso 50g", "Peso 20g", "Peso 10g", "Peso 5g", 
        "Peso 2g", "Peso 1g", "Cronômetro Digital", "Termo-higrômetro Digital", "Termo-higrômetro Digital", 
        "Termo-higrômetro Digital", "Termo-higrômetro Digital", "Termo-higrômetro Digital", "Luxímetro Digital"
    ]

    // Limpar equipamentos existentes para evitar conflitos se necessário, ou apenas upsert
    console.log("Iniciando semeadura de equipamentos...")

    for (const eq of caItems) {
        await prisma.equipment.upsert({
            where: { code: eq.code },
            update: eq,
            create: eq
        })
    }

    for (let i = 0; i < eqItems.length; i++) {
        const code = `EQ-${(i + 1).toString().padStart(3, '0')}`
        await prisma.equipment.upsert({
            where: { code: code },
            update: {
                name: eqItems[i],
                location: "Sala de Equipamentos",
                status: "ATIVO",
                acceptance: "Aprovado"
            },
            create: {
                code: code,
                name: eqItems[i],
                location: "Sala de Equipamentos",
                status: "ATIVO",
                acceptance: "Aprovado"
            }
        })
    }

    console.log(`Sucesso! ${caItems.length} itens CA e ${eqItems.length} itens EQ populados.`)
}

main()
    .catch((e) => {
        console.error(e)
        process.exit(1)
    })
    .finally(async () => {
        await prisma.$disconnect()
    })
